# Form implementation generated from reading ui file 'mainRPC.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(223, 315)
        MainWindow.setMinimumSize(QtCore.QSize(223, 315))
        MainWindow.setMaximumSize(QtCore.QSize(223, 315))
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.headsButton.setGeometry(QtCore.QRect(40, 160, 141, 41))
        self.headsButton.setObjectName("headsButton")
        self.tailsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tailsButton.setGeometry(QtCore.QRect(40, 210, 141, 41))
        self.tailsButton.setObjectName("tailsButton")
        self.usrScore = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.usrScore.setGeometry(QtCore.QRect(100, 60, 64, 23))
        self.usrScore.setObjectName("usrScore")
        self.userScoreLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.userScoreLabel.setGeometry(QtCore.QRect(50, 60, 47, 21))
        self.userScoreLabel.setObjectName("userScoreLabel")
        self.botScoreLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.botScoreLabel.setGeometry(QtCore.QRect(50, 90, 47, 21))
        self.botScoreLabel.setObjectName("botScoreLabel")
        self.botScore = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.botScore.setGeometry(QtCore.QRect(100, 90, 64, 23))
        self.botScore.setObjectName("botScore")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 260, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Boring RPC"))
        self.headsButton.setText(_translate("MainWindow", "Heads"))
        self.tailsButton.setText(_translate("MainWindow", "Tails"))
        self.userScoreLabel.setText(_translate("MainWindow", "User"))
        self.botScoreLabel.setText(_translate("MainWindow", "Bot"))


